name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]  # Run on every branch
  pull_request:
    branches: [ main, staging, production ]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  # Security and Quality Checks
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Audit dependencies
        run: npm audit --audit-level=moderate

  # Code Quality and Testing
  test-and-lint:
    name: Test & Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Lint code
        run: npm run lint

      - name: Check for tests
        run: |
          if [ -d "tests" ] || [ -f "jest.config.js" ]; then
            npm test --passWithNoTests
          else
            echo "No tests found, skipping test step"
          fi
        env:
          CI: true

  # Build and Performance Tests
  build-and-performance:
    name: Build & Performance
    runs-on: ubuntu-latest
    needs: [security-scan, test-and-lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NODE_ENV: production

  # E2E Testing (Optional - only if Playwright is configured)
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: [build-and-performance]
    if: github.event_name == 'pull_request' || contains(fromJSON('["staging", "production"]'), github.ref_name)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for E2E tests
        run: |
          if [ -f "playwright.config.ts" ] || [ -f "playwright.config.js" ]; then
            npx playwright install --with-deps
            npm run e2e
          else
            echo "No E2E tests configured, skipping"
          fi
        env:
          NODE_ENV: test
